### ISSUE TITLE
Feature request: allow to pass digest instead of message

### ISSUE THREAD

**Issue by xi** [pyauth/tsp-client#4]
tsp-client takes a message and hashes it. This is inefficient for large files because they have to be help in memory. Python 3.11 added helper functions for efficient hashing of files: https://docs.python.org/3/library/hashlib.html#file-hashing. It would be nice if we were able to use them.

I propose the extend the interface of `TSPSigner.sign()` so that it takes either a message or a digest. That would allow users to pass a digest without breaking backwards compatibility.

**Comment by kislyuk** [comment]
That sounds great! I'm in favor of this, PRs are welcome or I'll get to it sometime in the next few months.
